### ISSUE TITLE
Docs: Example 6 output cannot be read

### ISSUE THREAD

**Issue by bersbersbers** [cgnieder/acro#190]
I only see "We use the Universal", and so I think I am missing the point of this example:

![image](https://user-images.githubusercontent.com/12128514/99974588-70c6e680-2da1-11eb-8056-05fefbf1e7cd.png)

**Comment by cgnieder** [comment]
I don't understand your question. If I open the manual with
```
texdoc acro
```
navigate to example 6 and either click on the image or the [PDF] link a file called `acro.example.issue-154.pdf` opens which shows

![image](https://user-images.githubusercontent.com/2248538/100007342-3b83be00-2dcc-11eb-938c-fe1c7beb9294.png)

Likewise if I click [TeX] a file called `acro.example.issue-154.tex` opens which contains these lines:

```latex
\documentclass{article}

\usepackage[version=3]{acro}

\RenewAcroCommand\ac{mo}{\UseAcroTemplate{first}{#1}\IfNoValueF{#2}{#2}}

\DeclareAcronym{uc}{
  short = UC ,
  long = Universal Composability ,
  cite = xxx
}

\begin{document}

We use the \ac{uc}[ model] for\dots

\end{document}
```
The small picture in the left of the example boxes show the exact same clipping of the example PDF.

**Comment by bersbersbers** [comment]
I see. Well, I open http://mirrors.ctan.org/macros/latex/contrib/acro/acro-manual.pdf in Chrome. The TeX link downloads a `.tex` file, alright. But the PDF link scrolls to the top of the document. And the "preview" on the right is incomplete, as you see in the snapshot in my original post ("We use the Universal"). When I click that, again, it scrolls to the top of the document.

**Comment by cgnieder** [comment]
Well, then maybe you should open the example files directly – http://mirrors.ctan.org/macros/latex/contrib/acro/examples or https://github.com/cgnieder/acro/tree/master/doc/examples for example.

In the manual the links are _relative_ links which is why they work when you open the file with `texdoc` on your machine but not if you download it from some link in the internet.

And again: the small window is an _automatic_ clip from the PDF. If I change the output window for that example it changes for _all_ examples – and I have to make some compromise… I could show the complete page but then it were so small that you couldn't see anything. Or I could leave image and code snippet away and just refer to the example documents…

**Comment by bersbersbers** [comment]
I see. Alright, if everything works as intended ... ;)
